name: Update data

on:
  push:
    paths:
    - 'base_data_IBE.csv'

jobs:
  update_data:
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.0.3'
    - uses: r-lib/actions/setup-renv@v2
    
    - name: Prepare data with prepareData.R
      run: Rscript prepareData.R

    - name: commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Update Bildung_LernplattformMindsteps.csv
        branch: ${{ github.head_ref }}
