name: Update data

on:
  push:
    paths:
    - 'base_data_IBE.csv'

jobs:
  update_data:
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-renv@v2
    
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Prepare data with prepareData.R
      run: | 
        source('prepareData.R')
      shell: Rscript {0}

    # Commit to repo with updated file
    - name: commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Update Bildung_LernplattformMindsteps.csv
        branch: ${{ github.head_ref }}
